import { Card } from '../types';

/**
 * Sample Fair Play Deck Cards
 * 50+ cards covering all categories with English & Hebrew translations
 */

export const sampleCards: Card[] = [
  // DAILY-GRIND: 15 cards
  {
    id: 'card-001',
    category: 'daily-grind',
    title: { en: 'Morning Dishes', he: 'כלים בבוקר' },
    description: { en: 'Wash breakfast dishes', he: 'לשטוף כלים של ארוחת בוקר' },
    details: { en: 'Every morning after breakfast', he: 'כל בוקר אחרי ארוחה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'morning', 'kitchen'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 15,
    },
    history: [],
  },
  {
    id: 'card-002',
    category: 'daily-grind',
    title: { en: 'Dinner Prep', he: 'הכנת ארוחת ערב' },
    description: { en: 'Plan and prepare dinner', he: 'לתכנן ולהכין ארוחת ערב' },
    details: { en: '5 days per week', he: '5 ימים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'cooking', 'evening'],
      difficulty: 2,
      frequency: 'daily',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-003',
    category: 'daily-grind',
    title: { en: 'Kitchen Cleanup', he: 'ניקוי המטבח' },
    description: { en: 'Wipe counters and sweep floor', he: 'לנגב קאונטרים ולסחוף רצפה' },
    details: { en: 'After meals', he: 'אחרי ארוחות' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'cleaning', 'kitchen'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-004',
    category: 'daily-grind',
    title: { en: 'Evening Dishes', he: 'כלים בערב' },
    description: { en: 'Load dishwasher or hand wash', he: 'לטעון מדיח או לשטוף ביד' },
    details: { en: 'After dinner', he: 'אחרי ארוחת ערב' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'evening', 'kitchen'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-005',
    category: 'daily-grind',
    title: { en: 'Laundry Run', he: 'כביסה' },
    description: { en: 'Wash, dry, and fold clothes', he: 'לכבס, להשיק ולקפל ביגוד' },
    details: { en: '2-3 times per week', he: '2-3 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'laundry', 'housework'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-006',
    category: 'daily-grind',
    title: { en: 'Trash & Recycling', he: 'אשפה והקטנת פסולת' },
    description: { en: 'Take out trash and recycling', he: 'להוציא אשפה והקטנת פסולת' },
    details: { en: '2 times per week', he: '2 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'cleaning', 'maintenance'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 15,
    },
    history: [],
  },
  {
    id: 'card-007',
    category: 'daily-grind',
    title: { en: 'Bathroom Cleaning', he: 'ניקוי חדר האמבטיה' },
    description: { en: 'Clean toilet, sink, and floor', he: 'לנקות שירותים, כיור ורצפה' },
    details: { en: 'Weekly', he: 'שבועי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'cleaning'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-008',
    category: 'daily-grind',
    title: { en: 'Grocery Shopping', he: 'קניות מכולת' },
    description: { en: 'Weekly grocery run', he: 'קניות מכולת שבועיות' },
    details: { en: 'Once per week', he: 'פעם בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'shopping', 'planning'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-009',
    category: 'daily-grind',
    title: { en: 'Meal Planning', he: 'תכנון ארוחות' },
    description: { en: 'Plan weekly meals', he: 'לתכנן ארוחות לשבוע' },
    details: { en: 'Sunday evening', he: 'יום ראשון בערב' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'planning', 'cooking'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-010',
    category: 'daily-grind',
    title: { en: 'Vaccum Living Room', he: 'שאיבת הסלון' },
    description: { en: 'Vacuum and tidy living room', he: 'לשאוב ולסדר את הסלון' },
    details: { en: 'Weekly', he: 'שבועי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'cleaning', 'tidying'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 25,
    },
    history: [],
  },
  {
    id: 'card-011',
    category: 'daily-grind',
    title: { en: 'Bedsheet Change', he: 'החלפת סדינים' },
    description: { en: 'Change all bed sheets', he: 'להחליף סדינים בכל המיטות' },
    details: { en: 'Weekly', he: 'שבועי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'cleaning', 'bedrooms'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-012',
    category: 'daily-grind',
    title: { en: 'Inventory Check', he: 'בדיקת מלאי' },
    description: { en: 'Check pantry and fridge', he: 'לבדוק את הסידור וההיגייה' },
    details: { en: 'Weekly before shopping', he: 'שבועי לפני קניות' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'planning', 'kitchen'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 15,
    },
    history: [],
  },
  {
    id: 'card-013',
    category: 'daily-grind',
    title: { en: 'Pay Bills', he: 'תשלום חשבונות' },
    description: { en: 'Pay monthly bills online', he: 'לשלם חשבונות חודשיים' },
    details: { en: 'Once per month', he: 'פעם בחודש' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'finance', 'admin'],
      difficulty: 1,
      frequency: 'monthly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-014',
    category: 'daily-grind',
    title: { en: 'Deep Clean Kitchen', he: 'ניקוי עמוק של המטבח' },
    description: { en: 'Clean appliances and deep clean', he: 'לנקות מכשירים וניקוי עמוק' },
    details: { en: 'Monthly', he: 'חודשי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'cleaning', 'kitchen'],
      difficulty: 3,
      frequency: 'monthly',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-015',
    category: 'daily-grind',
    title: { en: 'Organize Pantry', he: 'ארגון המטבח' },
    description: { en: 'Organize and reorganize pantry', he: 'לארגן ולהסדר את המטבח' },
    details: { en: 'Monthly', he: 'חודשי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'organizing', 'kitchen'],
      difficulty: 2,
      frequency: 'monthly',
      timeEstimate: 60,
    },
    history: [],
  },

  // KIDS: 15 cards
  {
    id: 'card-016',
    category: 'kids',
    title: { en: 'Morning Routine Help', he: 'עזרה בשגרת הבוקר' },
    description: { en: 'Help kids get ready for school', he: 'לעזור לילדים להתכונן לבית ספר' },
    details: { en: 'School days 6:30-8:00am', he: 'ימי בית ספר 6:30-8:00' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'morning'],
      difficulty: 2,
      frequency: 'daily',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-017',
    category: 'kids',
    title: { en: 'Pack Lunches', he: 'הכנת קופסות אוכל' },
    description: { en: 'Pack school lunches', he: 'לארוז קופסות אוכל לבית ספר' },
    details: { en: 'Daily before school', he: 'כל יום לפני בית ספר' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'cooking'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-018',
    category: 'kids',
    title: { en: 'School Pickup/Dropoff', he: 'הבאה והסעה לבית ספר' },
    description: { en: 'Drive to/from school', he: 'לנהוג לבית ספר ממנו' },
    details: { en: 'Daily 8am and 2:45pm', he: 'כל יום 8:00 ו 14:45' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'transport'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-019',
    category: 'kids',
    title: { en: 'Homework Help', he: 'עזרה בעבודות בית' },
    description: { en: 'Help with homework and reading', he: 'לעזור עם עבודות בית וקריאה' },
    details: { en: '3-4 times per week', he: '3-4 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'education'],
      difficulty: 2,
      frequency: 'daily',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-020',
    category: 'kids',
    title: { en: 'Kids Bath Time', he: 'אמבטיה לילדים' },
    description: { en: 'Bath and nighttime routine', he: 'אמבטיה ושגרת לילה' },
    details: { en: 'Weeknight evenings', he: 'ערבי שישי - שלישי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'evening'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-021',
    category: 'kids',
    title: { en: 'Bedtime Stories', he: 'סיפורים לפני שינה' },
    description: { en: 'Read bedtime stories', he: 'לקרוא סיפורים לפני שינה' },
    details: { en: 'Weeknights 8pm', he: 'ערבי שישי - שלישי 20:00' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'bonding'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-022',
    category: 'kids',
    title: { en: 'Dentist/Doctor Appointments', he: 'תורים לרופא וציטור' },
    description: { en: 'Schedule and attend appointments', he: 'לתאם ולהביא לתורים' },
    details: { en: 'As needed', he: 'לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'kids', 'admin'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-023',
    category: 'kids',
    title: { en: 'Extracurricular Activities', he: 'פעילויות חוצ-כיתתיות' },
    description: { en: 'Drive to sports/music lessons', he: 'הסעה לספורט והצגות' },
    details: { en: '2-3 times per week', he: '2-3 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'kids', 'activities'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-024',
    category: 'kids',
    title: { en: 'Buy School Supplies', he: 'קנייה של ציוד בית ספר' },
    description: { en: 'Purchase supplies for school', he: 'לקנות ציוד בית ספר' },
    details: { en: 'As needed, mostly Sept', he: 'לפי הצורך, בעיקר בספטמבר' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'kids', 'shopping'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-025',
    category: 'kids',
    title: { en: 'Organize Closets', he: 'ארגון של ארונות' },
    description: { en: 'Organize seasonal clothes', he: 'לארגן ביגוד עונתי' },
    details: { en: 'Twice yearly', he: 'פעמיים בשנה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['seasonal', 'kids', 'organizing'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-026',
    category: 'kids',
    title: { en: 'Parent-Teacher Conferences', he: 'פגישות אחרי כתה' },
    description: { en: 'Attend school meetings', he: 'להשתתף בפגישות בית ספר' },
    details: { en: 'Twice per year', he: 'פעמיים בשנה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'kids', 'school'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-027',
    category: 'kids',
    title: { en: 'Birthday Party Planning', he: 'תכנון יום הולדת' },
    description: { en: 'Plan and organize birthday party', he: 'לתכנן ולארגן מסיבת יום הולדת' },
    details: { en: 'As needed', he: 'לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'kids', 'celebration'],
      difficulty: 3,
      frequency: 'occasional',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-028',
    category: 'kids',
    title: { en: 'Kids Chores Supervision', he: 'פיקוח על חובות הילדים' },
    description: { en: 'Oversee kids do their chores', he: 'לפקח שהילדים עושים חובות' },
    details: { en: '3-4 times per week', he: '3-4 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'kids', 'responsibility'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-029',
    category: 'kids',
    title: { en: 'Child Medical Care', he: 'טיפול רפואי לילדים' },
    description: { en: 'Manage meds and health needs', he: 'לנהל תרופות וצרכים בריאותיים' },
    details: { en: 'Daily as needed', he: 'כל יום לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'kids', 'health'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 15,
    },
    history: [],
  },
  {
    id: 'card-030',
    category: 'kids',
    title: { en: 'Weekend Adventure', he: 'הרפתקה בסופי שבוע' },
    description: { en: 'Plan fun activity with kids', he: 'לתכנן פעילות כיפיות עם ילדים' },
    details: { en: 'Weekend', he: 'סוף שבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'kids', 'bonding'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 120,
    },
    history: [],
  },

  // HOME: 15 cards
  {
    id: 'card-031',
    category: 'home',
    title: { en: 'Yard Work', he: 'עבודה בחצר' },
    description: { en: 'Mow lawn and edge', he: 'לכסוח את הדשא ולהדק קצוות' },
    details: { en: 'Every 1-2 weeks', he: 'כל שבועיים' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'yard', 'maintenance'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-032',
    category: 'home',
    title: { en: 'Garden Watering', he: 'השקיית הגן' },
    description: { en: 'Water plants and garden', he: 'להשקות צמחים וגן' },
    details: { en: '2-3 times per week', he: '2-3 פעמים בשבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'garden', 'plants'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-033',
    category: 'home',
    title: { en: 'Car Maintenance', he: 'תחזוקת הרכב' },
    description: { en: 'Gas, oil changes, inspections', he: 'דלק, שינוי שמן, בדיקות' },
    details: { en: 'As needed', he: 'לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'car', 'maintenance'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-034',
    category: 'home',
    title: { en: 'Fix Broken Items', he: 'תיקון דברים שבורים' },
    description: { en: 'Repair household items', he: 'לתקן פריטים ביתיים' },
    details: { en: 'As needed', he: 'לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'repairs', 'maintenance'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-035',
    category: 'home',
    title: { en: 'Gutter Cleaning', he: 'ניקוי גופיות' },
    description: { en: 'Clean gutters and downspouts', he: 'לנקות גופיות וצינורות ניקוז' },
    details: { en: 'Twice yearly', he: 'פעמיים בשנה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['seasonal', 'maintenance', 'exterior'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-036',
    category: 'home',
    title: { en: 'HVAC Filter Change', he: 'החלפת מסנן אוויר' },
    description: { en: 'Replace HVAC filters', he: 'להחליף מסננים' },
    details: { en: 'Every 3 months', he: 'כל 3 חודשים' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'maintenance', 'hvac'],
      difficulty: 1,
      frequency: 'monthly',
      timeEstimate: 15,
    },
    history: [],
  },
  {
    id: 'card-037',
    category: 'home',
    title: { en: 'Pest Control', he: 'בקרת מזיקים' },
    description: { en: 'Manage pest control service', he: 'לנהל שירות בקרת מזיקים' },
    details: { en: 'Quarterly', he: 'רבעוני' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['quarterly', 'maintenance', 'outside'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-038',
    category: 'home',
    title: { en: 'House Deep Clean', he: 'ניקוי עמוק של הבית' },
    description: { en: 'Deep clean entire house', he: 'ניקוי עמוק של כל הבית' },
    details: { en: 'Every 2-3 months', he: 'כל 2-3 חודשים' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['seasonal', 'cleaning', 'deep-clean'],
      difficulty: 3,
      frequency: 'occasional',
      timeEstimate: 240,
    },
    history: [],
  },
  {
    id: 'card-039',
    category: 'home',
    title: { en: 'Windows & Mirrors', he: 'חלונות ומראות' },
    description: { en: 'Clean all windows and mirrors', he: 'לנקות כל חלונות ומראות' },
    details: { en: 'Monthly', he: 'חודשי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'cleaning'],
      difficulty: 1,
      frequency: 'monthly',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-040',
    category: 'home',
    title: { en: 'Organize Storage', he: 'ארגון אחסון' },
    description: { en: 'Organize closets and storage', he: 'לארגן ארונות ואחסון' },
    details: { en: 'Quarterly', he: 'רבעוני' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['quarterly', 'organizing'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-041',
    category: 'home',
    title: { en: 'Paint Touch-ups', he: 'תיקון צבע' },
    description: { en: 'Touch up paint on walls', he: 'לתיקן צבע על קירות' },
    details: { en: 'As needed', he: 'לפי הצורך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'maintenance', 'decor'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-042',
    category: 'home',
    title: { en: 'Pool/Spa Care', he: 'טיפול בבריכה' },
    description: { en: 'Maintain pool water and chemicals', he: 'לתחזוק בריכה וכימיקלים' },
    details: { en: 'Weekly', he: 'שבועי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'pool', 'maintenance'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-043',
    category: 'home',
    title: { en: 'Home Inspection', he: 'בדיקת בית' },
    description: { en: 'Check home systems', he: 'לבדוק מערכות הבית' },
    details: { en: 'Annually', he: 'שנתי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['annual', 'maintenance'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-044',
    category: 'home',
    title: { en: 'Seasonal Decorating', he: 'קישוט עונתי' },
    description: { en: 'Decorate for holidays', he: 'לקשט לחגים' },
    details: { en: 'Seasonal', he: 'עונתי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['seasonal', 'decorating'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-045',
    category: 'home',
    title: { en: 'Furniture Rearrange', he: 'סידור ריהוט' },
    description: { en: 'Move and rearrange furniture', he: 'להזיז ולסדר ריהוט' },
    details: { en: 'As desired', he: 'לפי הרצון' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['occasional', 'organizing', 'decor'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },

  // MAGIC: 12 cards
  {
    id: 'card-046',
    category: 'magic',
    title: { en: 'Date Night', he: 'ערב בחוץ עם בן/בת הזוג' },
    description: { en: 'Plan and execute date night', he: 'לתכנן וליצור ערב רומנטי' },
    details: { en: 'Monthly or as desired', he: 'חודשי או לפי הרצון' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'romance', 'couple-time'],
      difficulty: 2,
      frequency: 'monthly',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-047',
    category: 'magic',
    title: { en: 'Breakfast in Bed', he: 'ארוחת בוקר במיטה' },
    description: { en: 'Prepare special breakfast', he: 'להכין ארוחת בוקר מיוחדת' },
    details: { en: 'Surprise gift of love', he: 'מתנה הפתעה של אהבה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'romance', 'cooking'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-048',
    category: 'magic',
    title: { en: 'Massage Night', he: 'ערב עיסוי' },
    description: { en: 'Give a relaxing massage', he: 'לתת עיסוי מרגיע' },
    details: { en: 'Whenever needed', he: 'בכל עת שצוריך' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'romance', 'relaxation'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 45,
    },
    history: [],
  },
  {
    id: 'card-049',
    category: 'magic',
    title: { en: 'Love Notes', he: 'פתקי אהבה' },
    description: { en: 'Leave love notes around house', he: 'להשאיר פתקי אהבה בבית' },
    details: { en: 'Small gestures daily', he: 'תנועות קטנות כל יום' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'romance', 'small-gestures'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 5,
    },
    history: [],
  },
  {
    id: 'card-050',
    category: 'magic',
    title: { en: 'Movie Night', he: 'ערב סרטים' },
    description: { en: 'Cuddle movie night at home', he: 'ערב סרטים עם התקרבות' },
    details: { en: 'Weekly', he: 'שבועי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'romance', 'couple-time'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-051',
    category: 'magic',
    title: { en: 'Candle Dinner', he: 'ארוחה באור נרות' },
    description: { en: 'Cook special candlelit dinner', he: 'לבשל ארוחה רומנטית באור נרות' },
    details: { en: 'Special occasions or surprise', he: 'אירועים מיוחדים או הפתעה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'romance', 'cooking'],
      difficulty: 3,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-052',
    category: 'magic',
    title: { en: 'Flowers Surprise', he: 'הפתעת פרחים' },
    description: { en: 'Surprise with flowers', he: 'לתן הפתעה עם פרחים' },
    details: { en: 'Surprise gift', he: 'מתנת הפתעה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'romance', 'gift'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-053',
    category: 'magic',
    title: { en: 'Anniversary Celebration', he: 'חגיגת יום נישואין' },
    description: { en: 'Plan special anniversary', he: 'לתכנן ולחגוג שנה' },
    details: { en: 'Annual', he: 'שנתי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['annual', 'romance', 'celebration'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-054',
    category: 'magic',
    title: { en: 'Weekend Getaway', he: 'טיול סוף שבוע' },
    description: { en: 'Plan romantic weekend trip', he: 'לתכנן טיול זוגי' },
    details: { en: 'As desired', he: 'לפי הרצון' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'romance', 'travel'],
      difficulty: 3,
      frequency: 'occasional',
      timeEstimate: 240,
    },
    history: [],
  },
  {
    id: 'card-055',
    category: 'magic',
    title: { en: 'Morning Coffee Together', he: 'קפה בוקר ביחד' },
    description: { en: 'Share quiet coffee time', he: 'לשתות קפה שקט ביחד' },
    details: { en: 'Daily morning ritual', he: 'טקס בוקר יומי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['daily', 'romance', 'ritual'],
      difficulty: 1,
      frequency: 'daily',
      timeEstimate: 20,
    },
    history: [],
  },
  {
    id: 'card-056',
    category: 'magic',
    title: { en: 'Plan Date Ideas', he: 'תכנון רעיונות לדייט' },
    description: { en: 'Research and plan fun dates', he: 'לתכנן רעיונות דייט כיפיים' },
    details: { en: 'Monthly planning', he: 'תכנון חודשי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'romance', 'planning'],
      difficulty: 1,
      frequency: 'monthly',
      timeEstimate: 30,
    },
    history: [],
  },
  {
    id: 'card-057',
    category: 'magic',
    title: { en: 'Love Language Act', he: 'פעולת שפת אהבה' },
    description: { en: 'Express love in partner\'s language', he: 'להביע אהבה בדרך המועדפת' },
    details: { en: 'Weekly or more', he: 'שבועי או יותר' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'romance', 'connection'],
      difficulty: 1,
      frequency: 'weekly',
      timeEstimate: 30,
    },
    history: [],
  },

  // WILD: 10 cards
  {
    id: 'card-058',
    category: 'wild',
    title: { en: 'Adventure Day', he: 'יום הרפתקאות' },
    description: { en: 'Plan spontaneous adventure', he: 'לתכנן הרפתקה ספונטנית' },
    details: { en: 'Surprise adventure', he: 'הרפתקה בהפתעה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'adventure', 'spontaneous'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 240,
    },
    history: [],
  },
  {
    id: 'card-059',
    category: 'wild',
    title: { en: 'Karaoke Night', he: 'ערב קריוקי' },
    description: { en: 'Have fun singing together', he: 'לשיר וליהנות ביחד' },
    details: { en: 'Monthly or as desired', he: 'חודשי או לפי הרצון' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'fun', 'social'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 120,
    },
    history: [],
  },
  {
    id: 'card-060',
    category: 'wild',
    title: { en: 'Road Trip', he: 'טיול כביש' },
    description: { en: 'Plan a fun road trip', he: 'לתכנן טיול כביש כיפי' },
    details: { en: 'Adventure getaway', he: 'טיול הרפתקה' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'adventure', 'travel'],
      difficulty: 3,
      frequency: 'occasional',
      timeEstimate: 360,
    },
    history: [],
  },
  {
    id: 'card-061',
    category: 'wild',
    title: { en: 'Dance Party', he: 'מסיבת ריקוד' },
    description: { en: 'Have spontaneous dance party', he: 'לעשות מסיבת ריקוד ספונטנית' },
    details: { en: 'Whenever the mood strikes', he: 'בכל עת שהמצב מתאים' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['spontaneous', 'fun', 'activity'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-062',
    category: 'wild',
    title: { en: 'Outdoor Adventure', he: 'הרפתקה בחוץ' },
    description: { en: 'Hike or explore nature', he: 'לטייל או לחקור טבע' },
    details: { en: 'Weekend adventure', he: 'הרפתקת סוף שבוע' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekend', 'outdoor', 'adventure'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-063',
    category: 'wild',
    title: { en: 'New Recipe Challenge', he: 'אתגר מתכון חדש' },
    description: { en: 'Try cooking something new', he: 'לנסות לבשל משהו חדש' },
    details: { en: 'Weekly or monthly', he: 'שבועי או חודשי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['weekly', 'cooking', 'experiment'],
      difficulty: 2,
      frequency: 'weekly',
      timeEstimate: 90,
    },
    history: [],
  },
  {
    id: 'card-064',
    category: 'wild',
    title: { en: 'Concert or Festival', he: 'קונצרט או פסטיבל' },
    description: { en: 'Attend live music event', he: 'ללכת להופעה חיה' },
    details: { en: 'As opportunities arise', he: 'כשיש הזדמנויות' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['special', 'entertainment', 'social'],
      difficulty: 2,
      frequency: 'occasional',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-065',
    category: 'wild',
    title: { en: 'Sport Game Day', he: 'יום משחק ספורט' },
    description: { en: 'Attend or play sports together', he: 'להשתתף או לשחק ספורט ביחד' },
    details: { en: 'Seasonal', he: 'עונתי' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['seasonal', 'sports', 'activity'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 180,
    },
    history: [],
  },
  {
    id: 'card-066',
    category: 'wild',
    title: { en: 'Late Night Snack Run', he: 'טיול לחטיף בלילה' },
    description: { en: 'Midnight snack adventure', he: 'טיול לחטיפים בחצות הלילה' },
    details: { en: 'Spontaneous fun', he: 'כיף ספונטני' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['spontaneous', 'fun', 'food'],
      difficulty: 1,
      frequency: 'occasional',
      timeEstimate: 60,
    },
    history: [],
  },
  {
    id: 'card-067',
    category: 'wild',
    title: { en: 'Try New Restaurant', he: 'נסיון במסעדה חדשה' },
    description: { en: 'Explore new dining spot', he: 'לחקור מסעדה חדשה' },
    details: { en: 'Monthly or as desired', he: 'חודשי או לפי הרצון' },
    holder: null,
    status: 'unassigned',
    metadata: {
      createdAt: new Date(),
      modifiedAt: new Date(),
      isCustom: false,
      isActive: true,
      tags: ['monthly', 'food', 'exploration'],
      difficulty: 1,
      frequency: 'monthly',
      timeEstimate: 120,
    },
    history: [],
  },
];
